### ISSUE TITLE
Error loading custom configuration

### ISSUE THREAD

**Issue by nseba** [qiangyt/jog#43] opened 2020-08-16 16:26 UTC
Hello,

The jog tool is really awesome, but I've tried to provide it a custom configuration for better parsing pino logs using the -t option to generate a template. Unfortunately this fails with the following golang error:

```
home/seba/.jog.yaml: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `/home/s...` into map[string]interface {}
```

I'm not an experienced golang programmer, but I could track the following issue which seems to be related to this:
https://github.com/go-yaml/yaml/issues/139

**Comment by qiangyt** [comment] 2020-08-19 02:43
Which version of jog you're using?
And could you paste your home/seba/.jog.yaml ?

**Comment by qiangyt** [comment] 2020-09-21 03:48
Close bcause unable to reproduce and no further response from original reporter

**Comment by frudolph77** [comment] 2020-10-09 11:34
I just got the same error.

I'm using version 0.9.14
I've redirected the output of **jog -t** to .jog.yaml 

I would use this as a base to customize it, leaving it unchanged and starting jog leads to this error.

I've check the file with a yaml validators and it is valid.

**Comment by qiangyt** [comment] 2020-10-09 14:43
> I just got the same error.
> 
> I'm using version 0.9.14
> I've redirected the output of **jog -t** to .jog.yaml
> 
> I would use this as a base to customize it, leaving it unchanged and starting jog leads to this error.
> 
> I've check the file with a yaml validators and it is valid.
> 
> SMALL Update:
> using the very same file with the -c parameter works fine

I see your point and now can reproduce it, Thanks! Will fix it

**Comment by qiangyt** [comment] 2020-10-09 15:10
Fixed by commit: https://github.com/qiangyt/jog/commit/cea3edbb5f6c19079e21688d657a85a5587d4394.
Release v0.9.15 for this fix as well.

**Closed by qiangyt** 2020-10-09 15:10 UTC

**Comment by frudolph77** [comment] 2020-10-09 16:58
WOW, this was fast. Thanks, works like a charm.

**Comment by qiangyt** [comment] 2020-10-10 08:12
@frudolph77 , prev commit has a critical regression, please use new v0.9.15.1, instead
